version: '3.7'

services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - './react-app:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
