version: '3'

services:
  jira:
    depends_on:
      - db
    image: atlassian/jira-software
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian-data/jira # JIRA_HOME
    ports:
      - '8080:8080'
    environment:
      - ATL_DB_TYPE=postgres72
      - ATL_DB_DRIVER=org.postgresql.Driver #com.mysql.cj.jdbc.Driver 
      - ATL_JDBC_URL=jdbc:postgresql://db:5432/jiradb  #jdbc:mysql://db:3306/jiradb
      - ATL_DB_SCHEMA_NAME=public  #jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=root

    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  db:
    image: postgres:12.6-alpine
    networks:
      - jiranet
    volumes:
      - ./postgre_data:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=jira'
      # CHANGE THE PASSWORD!
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_DB=jiradb'
      - 'POSTGRES_ENCODING=UNICODE'
      - 'POSTGRES_COLLATE=C'
      - 'POSTGRES_COLLATE_TYPE=C'
    logging:
      # limit logs retained on host to 25MB
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - jiranet
volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge