version: '3'

volumes:
  db-data: {}
  jira-data: {}

services:
  jira:
    depends_on:
      - db
    restart: always
    networks:
      - jiranet
    image: atlassian/jira-software
    environment:
      - ATL_DB_TYPE=mysql
      - ATL_DB_DRIVER=com.mysql.cj.jdbc.Driver #com.mysql.cj.jdbc.Driver #com.mysql.jdbc.Driver
      - ATL_JDBC_URL=jdbc:mysql://db:3306/jiradb #mysql://jira@db/jiradb #jdbc:mysql://db:3306/jiradb
      - ATL_DB_SCHEMA_NAME=jiradb  #jiradb
      - ATL_JDBC_USER=jira
      - ATL_JDBC_PASSWORD=root
    ports:
      - 8080:8080
    volumes:
      - jira-data:/var/atlassian-data/jira # JIRA_HOME
  db:
    restart: always
    image: mysql:8
    networks:
      - jiranet
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jiradb
      - MYSQL_USER=jira
      - MYSQL_PASSWORD=root
    # command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin, --default-storage-engine=INNODB, --max_allowed_packet=256M, --innodb_log_file_size=2GB, --transaction-isolation=READ-COMMITTED, --binlog_format=row]
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - jiranet
networks:
    jiranet: {}